name: metapinn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - python=3.10.14
  - python_abi=3.10=3_cp310
  - matplotlib
  - scipy=1.12.0
  - pytorch=2.2.0
  - cudatoolkit=11.6.0
  - torchaudio=2.2.1
  - torchvision=0.17.1
  - tqdm=4.64.1
  - pip=22.3.1
  - pip:
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
